#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker3"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "050f7ca712924b36979cf7a2c93e070a" }
]
